# -*- coding: utf-8 -*-
"""Cluster_Predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18p2QzVC_KGkhczSmpCtiV1LJ-xXmid3I
"""

import json
import random
import joblib
import pandas as pd

from joblib import load
from google.colab import drive

# Mount Google Drive to access dataset
drive.mount('/content/drive', force_remount=True)

# Set up directory path
file_path = '/content/drive/MyDrive/model_kmeans.joblib'

# membuat dictionary yang akan dijadikan file JSON
data = {
  "EXT1": random.randint(1,5),"EXT2": random.randint(1,5),"EXT3": random.randint(1,5),"EXT4": random.randint(1,5),"EXT5": random.randint(1,5),"EXT6": random.randint(1,5),"EXT7": random.randint(1,5),"EXT8": random.randint(1,5),"EXT9": random.randint(1,5),"EXT10": random.randint(1,5),
  "EST1": random.randint(1,5),"EST2": random.randint(1,5),"EST3": random.randint(1,5),"EST4": random.randint(1,5),"EST5": random.randint(1,5),"EST6": random.randint(1,5),"EST7": random.randint(1,5),"EST8": random.randint(1,5),"EST9": random.randint(1,5),"EST10": random.randint(1,5),
  "AGR1": random.randint(1,5),"AGR2": random.randint(1,5),"AGR3": random.randint(1,5),"AGR4": random.randint(1,5),"AGR5": random.randint(1,5),"AGR6": random.randint(1,5),"AGR7": random.randint(1,5),"AGR8": random.randint(1,5),"AGR9": random.randint(1,5),"AGR10": random.randint(1,5),
  "CSN1": random.randint(1,5),"CSN2": random.randint(1,5),"CSN3": random.randint(1,5),"CSN4": random.randint(1,5),"CSN5": random.randint(1,5),"CSN6": random.randint(1,5),"CSN7": random.randint(1,5),"CSN8": random.randint(1,5),"CSN9": random.randint(1,5),"CSN10": random.randint(1,5),
  "OPN1": random.randint(1,5),"OPN2": random.randint(1,5),"OPN3": random.randint(1,5),"OPN4": random.randint(1,5),"OPN5": random.randint(1,5),"OPN6": random.randint(1,5),"OPN7": random.randint(1,5),"OPN8": random.randint(1,5),"OPN9": random.randint(1,5),"OPN10": random.randint(1,5)
}

# membuka file baru dengan mode write
with open('file.json', 'w') as f:
    # menuliskan data ke file JSON
    json.dump(data, f)

with open('file.json') as f:
    data = json.load(f)
    
# Mengubah dictionary menjadi DataFrame dan mengubah orientasi DataFrame menjadi format yang diinginkan
df = pd.DataFrame(data, index=[0])
df.head(20)

kmeans_model = joblib.load(file_path)
cluster_labels = int(kmeans_model.predict(df))

print(cluster_labels)